### ISSUE TITLE
Doesn't work via ssh

### ISSUE THREAD

**Issue by Guldoman** [adamharrison/quetta#4]
While in an ssh session, running `lpm run 2.1.5 --ephemeral https://github.com/adamharrison/lite-xl-plugins:PR/add-quetta quetta` results in SDL having problems initializing (as expected).
Running with `SDL_VIDEODRIVER=dummy` helps with the SDL initialization, but `quetta` still doesn't show up.
I suspect this might be related to #3.

**Comment by adamharrison** [comment]
This has been fixed.
